
#AddurDisc Settings
[common]
	#Changing this option so that en_us.json doesn't reset on startup,
	#which can help you change the name and description of the record
	#default : true
	refreshLang = true
	#You can customize the resource path name
	#default : .addurdisc
	CustomPathName = ".addurdisc"
	#You can change this option to control whether discs can be dropped by creeper.(true or false)
	#default : true
	CanDropByCreeper = true
	#You can customize the resource path(in game directory)
	#example1: .minecraft/config/ = "config"
	#example2: .minecraft/logs/addurdisc/ = "logs/addurdisc"
	CustomPath = ""

